#!/bin/bash

instance_id="i-0123456789abcdef0"
metric_name="CPUUtilization"
namespace="AWS/EC2"
period=300
start_time="$(date -u +%FT%TZ --date '-10 minutes')"
end_time="$(date -u +%FT%TZ --date '-5 minutes')"
statistics="Average"

aws cloudwatch get-metric-statistics \
    --metric-name $metric_name \
    --namespace $namespace \
    --dimensions Name=InstanceId,Value=$instance_id \
    --start-time $start_time \
    --end-time $end_time \
    --period $period \
    --statistics $statistics
